import java.math.BigInteger;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Main {

    public static void main(String[] args) {

        //------------------------------------------ Secure Hash Algorithms 256 -----------------------------------------------

        SHA256 sha256 = new SHA256();
        System.out.println("HashCode Generated by SHA-256 for:");
        String s1 = "rezz";
        System.out.println("\n" + s1 + " : " + sha256.encryptThisString(s1));
        String s2 = "hello world";
        System.out.println("\n" + s2 + " : " + sha256.encryptThisString(s2));

        //------------------------------------------ Secure Hash Algorithms 512 -----------------------------------------------

        SHA512 sha512 = new SHA512();
        System.out.println("HashCode Generated by SHA-512 for: ");
        String s3 = "GeeksForGeeks";
        System.out.println("\n" + s1 + " : " + sha512.encryptThisString(s3));
        String s4 = "hello world";
        System.out.println("\n" + s2 + " : " + sha512.encryptThisString(s4));

    }
}
